version: '2.3'

services:
  worker:
    container_name: lin-worker
    image: itamtao/pytorch-mpi:cuda9
    shm_size: 8G
    volumes:
      - /mlo-container-scratch/tlin/:/mlodata1/tlin
    command: ["sleep", "infinity"]
    runtime: nvidia
    environment:
      JOBMONITOR_TIMESERIES_HOST: lin-timeseries
      JOBMONITOR_METADATA_HOST: lin-metadata
    networks:
      - net
  # notebook:
  #   container_name: lin-notebook
  #   image: itamtao/notebook
  #   user: root
  #   working_dir: /mlodata1/tlin
  #   volumes:
  #     - /mlo-container-scratch/tlin/:/mlodata1/tlin
  #   command: ["start-notebook.sh", "--NotebookApp.token=''"]
  #   runtime: nvidia
  #   environment:
  #     NB_UID: 144057
  #     NB_GID: 11169
  #     JOBMONITOR_TIMESERIES_HOST: lin-timeseries
  #     JOBMONITOR_METADATA_HOST: lin-metadata
  #     CHOWN_HOME: 'yes'
  #     CHOWN_HOME_OPTS: -R
  #   networks:
  #     - net
  #   ports:
  #     - 18888:8888
networks:
  net:
